export const pricingPlans = [
  {
    id: "free",
    name: "FREE",
    price: 0,
    originalPrice: null,
    saveText: null,
    credits: 10,
    description: "Perfect for trying Job Autopilot",
    features: [
      "10 credits per month",
      "Resume generation",
      "Cover letter generation",
      "Basic support",
    ],
    popular: false,
    badges: [],
    limitedBadge: null,
    cta: "Start Free",
  },
  {
    id: "pro",
    name: "Pro",
    price: 14.99,
    originalPrice: 24.99,
    saveText: "Save 40%",
    credits: 150,
    description: "Best for active job hunters",
    features: [
      "150 credits per month",
      "Everything in Free",
      "Priority generation",
      "Priority support",
    ],
    popular: true,
    badges: ["Most Popular"],
    limitedBadge: "Limited Time Offer",
    cta: "Start Pro",
  },
  {
    id: "team",
    name: "Team",
    price: 19.99,
    originalPrice: 34.99,
    saveText: "Save 43%",
    credits: 300,
    description: "Higher monthly limit for heavy usage",
    features: [
      "300 credits per month",
      "Everything in Pro",
      "Team sharing",
      "Higher monthly limit",
    ],
    popular: false,
    badges: ["Best Value"],
    limitedBadge: null,
    cta: "Start Team",
  },
];
